# cloudbuild-dev.yaml (Dev-Umgebung)
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fints-app:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fints-app:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'fints-dev', '--image', 'gcr.io/$PROJECT_ID/fints-app:$BUILD_ID', '--region', 'us-central1', '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY